"""Infrastructure adapters for external tools."""

from jp_learning_platform.infrastructure.audio_loader import (
    AudioFileNotFoundError,
    AudioFormat,
    AudioLoader,
    AudioLoaderError,
    EmptyAudioFileError,
    LoadedAudio,
    UnsupportedAudioFormatError,
)
from jp_learning_platform.infrastructure.artifact_store import (
    InvalidStageArtifactRecordError,
    STAGE_ARTIFACT_FILENAMES,
    StageArtifactSerializationError,
    StageArtifactStore,
    StageArtifactStoreError,
)
from jp_learning_platform.infrastructure.console_progress import (
    ConsoleProgressReporter,
)
from jp_learning_platform.infrastructure.faster_whisper_transcriber import (
    DEFAULT_WHISPER_COMPUTE_TYPE,
    DEFAULT_WHISPER_DEVICE,
    DEFAULT_WHISPER_MODEL_SIZE,
    FasterWhisperDependencyError,
    FasterWhisperTranscriber,
)
from jp_learning_platform.infrastructure.listening_json_writer import (
    DEFAULT_LISTENING_JSON_EXTENSION,
    LISTENING_JSON_SCHEMA_VERSION,
    CompositeSubtitleWriter,
    ListeningJsonWriter,
)
from jp_learning_platform.infrastructure.pipeline_config import (
    DEFAULT_QWEN_REPAIR_CONFIG,
    DEFAULT_QWEN_REPAIR_SAFETY_CONFIG,
    DEFAULT_READABILITY_CONFIG,
    DEFAULT_SUBTITLE_MERGE_CONFIG,
    DEFAULT_WHISPER_TRANSCRIPTION_CONFIG,
    DEFAULT_WHISPERX_ALIGNMENT_CONFIG,
    QwenRepairConfig,
    QwenRepairSafetyConfig,
    ReadabilityConfig,
    SubtitleMergeConfig,
    WhisperTranscriptionConfig,
    WhisperXAlignmentConfig,
)
from jp_learning_platform.infrastructure.qwen_repairer import (
    DEFAULT_QWEN_CONTEXT,
    DEFAULT_QWEN_GPU_LAYERS,
    DEFAULT_QWEN_MAX_TOKENS,
    DEFAULT_QWEN_REPEAT_PENALTY,
    DEFAULT_QWEN_REPAIR_MAX_CONTENT_CHANGE_RATIO,
    DEFAULT_QWEN_REPAIR_MAX_LENGTH_DELTA_RATIO,
    DEFAULT_QWEN_TEMPERATURE,
    DEFAULT_QWEN_TOP_P,
    DEFAULT_QWEN_THREADS,
    LlamaCppQwenRepairer,
    PassthroughQwenRepairer,
    QwenDependencyError,
    QwenModelNotFoundError,
    QwenRepairSafetyDecision,
    QwenRepairSafetyPolicy,
    QwenRepairSafetyReason,
)
from jp_learning_platform.infrastructure.srt_subtitle_writer import (
    SrtSubtitleWriter,
    format_srt_subtitle,
    format_srt_timestamp,
)
from jp_learning_platform.infrastructure.subtitle_quality import (
    ConservativeSubtitleMerger,
    DomainSubtitleValidator,
    LocalReadabilityOptimizer,
)
from jp_learning_platform.infrastructure.tool_registry import (
    DuplicateToolError,
    RegisteredTool,
    ToolNotFoundError,
    ToolRegistry,
    ToolRegistryError,
)
from jp_learning_platform.infrastructure.whisperx_aligner import (
    DEFAULT_WHISPERX_LANGUAGE,
    PassthroughWhisperXAligner,
    WhisperXAlignerAdapter,
    WhisperXDependencyError,
)
from jp_learning_platform.infrastructure.word_subtitle_builder import (
    WordSubtitleBuilder,
)

__all__ = [
    "AudioFileNotFoundError",
    "AudioFormat",
    "AudioLoader",
    "AudioLoaderError",
    "ConservativeSubtitleMerger",
    "ConsoleProgressReporter",
    "CompositeSubtitleWriter",
    "DEFAULT_LISTENING_JSON_EXTENSION",
    "LISTENING_JSON_SCHEMA_VERSION",
    "DEFAULT_QWEN_CONTEXT",
    "DEFAULT_QWEN_GPU_LAYERS",
    "DEFAULT_QWEN_MAX_TOKENS",
    "DEFAULT_QWEN_REPEAT_PENALTY",
    "DEFAULT_QWEN_REPAIR_CONFIG",
    "DEFAULT_QWEN_REPAIR_MAX_CONTENT_CHANGE_RATIO",
    "DEFAULT_QWEN_REPAIR_MAX_LENGTH_DELTA_RATIO",
    "DEFAULT_QWEN_REPAIR_SAFETY_CONFIG",
    "DEFAULT_QWEN_TEMPERATURE",
    "DEFAULT_QWEN_TOP_P",
    "DEFAULT_QWEN_THREADS",
    "DEFAULT_READABILITY_CONFIG",
    "DEFAULT_SUBTITLE_MERGE_CONFIG",
    "DEFAULT_WHISPER_COMPUTE_TYPE",
    "DEFAULT_WHISPER_DEVICE",
    "DEFAULT_WHISPER_MODEL_SIZE",
    "DEFAULT_WHISPER_TRANSCRIPTION_CONFIG",
    "DEFAULT_WHISPERX_ALIGNMENT_CONFIG",
    "DEFAULT_WHISPERX_LANGUAGE",
    "DomainSubtitleValidator",
    "DuplicateToolError",
    "EmptyAudioFileError",
    "FasterWhisperDependencyError",
    "FasterWhisperTranscriber",
    "InvalidStageArtifactRecordError",
    "LlamaCppQwenRepairer",
    "ListeningJsonWriter",
    "LocalReadabilityOptimizer",
    "LoadedAudio",
    "PassthroughQwenRepairer",
    "PassthroughWhisperXAligner",
    "QwenDependencyError",
    "QwenModelNotFoundError",
    "QwenRepairConfig",
    "QwenRepairSafetyDecision",
    "QwenRepairSafetyConfig",
    "QwenRepairSafetyPolicy",
    "QwenRepairSafetyReason",
    "ReadabilityConfig",
    "RegisteredTool",
    "SrtSubtitleWriter",
    "STAGE_ARTIFACT_FILENAMES",
    "StageArtifactSerializationError",
    "StageArtifactStore",
    "StageArtifactStoreError",
    "SubtitleMergeConfig",
    "ToolNotFoundError",
    "ToolRegistry",
    "ToolRegistryError",
    "UnsupportedAudioFormatError",
    "WhisperXAlignerAdapter",
    "WhisperTranscriptionConfig",
    "WhisperXAlignmentConfig",
    "WhisperXDependencyError",
    "WordSubtitleBuilder",
    "format_srt_subtitle",
    "format_srt_timestamp",
]
